// This file is automatically generated. Do not edit it directly.
import { createClient, SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Проверка наличия обязательных переменных окружения
if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY || 
    SUPABASE_URL === 'your_supabase_project_url_here' || 
    SUPABASE_PUBLISHABLE_KEY === 'your_supabase_anon_key_here') {
  console.error('❌ Supabase configuration is missing!');
  console.error('Please add the following to your .env.local file:');
  console.error('VITE_SUPABASE_URL=https://your-project.supabase.co');
  console.error('VITE_SUPABASE_PUBLISHABLE_KEY=your_anon_key');
  console.error('');
  console.error('To get these values:');
  console.error('1. Go to https://app.supabase.com');
  console.error('2. Select your project (or create a new one)');
  console.error('3. Go to Settings -> API');
  console.error('4. Copy "Project URL" and "anon public" key');
  console.error('');
  console.error('⚠️ App will continue with a mock client, but database features will not work.');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Создаем клиент только если есть валидные значения
let supabase: SupabaseClient<Database>;

if (SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY && 
    SUPABASE_URL !== 'your_supabase_project_url_here' && 
    SUPABASE_PUBLISHABLE_KEY !== 'your_supabase_anon_key_here') {
  supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
} else {
  // Создаем заглушку для разработки
  supabase = createClient<Database>(
    'https://placeholder.supabase.co',
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0',
    {
      auth: {
        storage: localStorage,
        persistSession: true,
        autoRefreshToken: true,
      }
    }
  );
}

export { supabase };
